[SWA-67][FEAT] - Update existing Arbitrum $USDC into $USDC.e
SwaprHQ/swapr-sdk pull request #313
Opened 2023-06-22 12:55 UTC by ElRodrigote

## Fixes: [SWA-67](https://linear.app/swaprdev/issue/SWA-67/update-usdc-token-in-arbitrum)

# Description

* Update existing (bridged) Arbitrum $USDC into $USDC.e as Circle is creating a native version for $USDC in this chain
* More info: https://arbitrumfoundation.medium.com/usdc-to-come-natively-to-arbitrum-f751a30e3d83

2023-06-26 13:46 UTC, berteotti requested changes
~We should add native USDC too on this PR.~ Never mind, I think it's smoother to rename USDC token for now. Will approve when dist folder is removed.

2023-06-26 13:48 UTC, berteotti commented on src/entities/trades/uniswap-v2/constants.ts
> +    'Bridged USDC'
I think we should change this to Native instead of Bridged. Am I seeing something wrong here?

2023-06-26 15:54 UTC, ElRodrigote commented
> We should add native USDC too on this PR.

I added it over the [dApp PR](https://github.com/SwaprHQ/swapr-dapp/pull/1843/files#diff-938d5a29ac7028fc98c349ad84eb7e578ecd35b9b0bb6f857538a3d339d84a33R77)

> ~We should add native USDC too on this PR.~ Never mind, I think it's smoother to rename USDC token for now. Will approve when dist folder is removed.

`dist` folder removed!

2023-06-28 13:51 UTC, berteotti approved these changes
Looks good to me!

2023-06-28 15:50 UTC, merged